"""CPPython managed base ConanFile.

This file is auto-generated by CPPython. Do not edit manually.
Dependencies and layout are managed through pyproject.toml.
"""

from conan import ConanFile


class CPPythonBase(ConanFile):
    """Base ConanFile with CPPython managed dependencies and layout."""

    def layout(self):
        """CPPython managed layout for consistent paths across all platforms.

        Uses explicit folder settings instead of cmake_layout() to avoid
        platform/generator-dependent behavior (e.g., build_type subfolders
        on single-config generators).
        """
        self.folders.build = "."
        self.folders.generators = "generators"

    def requirements(self):
        """CPPython managed requirements."""
        self.requires("honesty/[>=0.0.0.dev1]")
        self.requires("periapsis/[>=0.0.0.dev1]")
        self.requires("cppaste/[>=0.0.0.dev1]")
        self.requires("portability/[>=0.0.0.dev1]")
        self.requires("sdl/[>=3.2.20]")
        self.requires("vulkan-memory-allocator/3.3.0")
        self.requires("glaze/[>=6.0.1]")
        self.requires("freetype/2.14.1")
        self.requires("meshoptimizer/0.25")

    def build_requirements(self):
        """CPPython managed build and test requirements."""
        pass  # No test requirements
